index:
  path: /{_locale}
  controller: VP\PersonalAccount\Controller\UserController::action
  requirements:
    _locale: '%app_locales%'
  defaults:
    template: users/user.html.twig
    _locale: '%locale%'