homepage:
  path: /{_locale}
  controller: VP\PersonalAccount\Controller\UserController::authorization
  requirements:
    _locale: '%app_locales%'
  defaults:
    template: default/homepage.html.twig
    _locale: '%locale%'