index:
  path: /{_locale}
  controller: VP\PersonalAccount\Controller\IndexController::show
  requirements:
    _locale: '%app_locales%'
  defaults:
    template: security/security.html.twig
    _locale: '%locale%'