swiftmailer:
  delivery_addresses: ['pivovarchyk@tut.by']
  transport:  '%env(MAIL_YANDEX_TRANSPORT)%'
  encryption: '%env(MAIL_YANDEX_ENCRYPTION)%'
  auth_mode:  '%env(MAIL_AUTH_MODE)%'
  host:       '%env(MAIL_YANDEX_HOST)%'
  username:   '%env(MAIL_YANDEX_USERNAME)%'
  password:   '%env(MAIL_YANDEX_PASSWORD)%'
  port:       '%env(MAIL_YANDEX_PORT)%'