# config/packages/security.yaml
security:
    providers:
        user:
            entity:
                class: 'VP\PersonalAccount\Entity\User'
    encoders:
        VP\PersonalAccount\Entity\User:
            algorithm: auto
    access_control:
        #- { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        #- { path: ^/login$, roles: ROLE_USER}
        #- { path: ^/, roles: IS_AUTHENTICATED_FULLY }
        #- { path: ^/, roles:  ROLE_ADMIN}
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            pattern: ^/
            form_login:
                login_path: login
                check_path: login
                #always_use_default_target_path: true
                default_target_path: homepage
                #target_path_parameter: go_to
                #failure_path_parameter: back_to
            logout:
                path: logout
                target: index
            guard:
                authenticators:
                  - VP\PersonalAccount\Security\LoginFormAuthentificator
        secured_area:
            form_login:
                csrf_token_generator: security.csrf.token_manager